#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config split_ratio   0.7


bspc config border_width 1
bspc config window_gap -1
for side in top right bottom left ; do
	bspc config ${side}_padding 1
done

bspc config top_padding   -1
bspc config top_monocle_padding -1

# automatic_scheme 0
# split_ratio
# window_gap
# right_padding
# bottom_padding
# left_padding
# top_monocle_padding
# right_monocle_padding
# bottom_monocle_padding
# left_monocle_padding
# border_width
# normal_border_color
# focused_border_color
# active_border_color
# borderless_monocle
# gapless_monocle
# single_monocle
# click_to_focus
# focus_follows_pointer
# center_pseudo_tiled
# directional_focus_tightness
# external_rules_command
# honor_size_hints
# merge_overlapping_monitors
# initial_polarity
# mapping_events_count
# presel_feedback
# presel_feedback_color
# removal_adjustment
# remove_disabled_monitors
# remove_unplugged_monitors
# status_prefix
# swallow_first_click
# ignore_ewmh_focus
# ignore_ewmh_fullscreen
# ignore_ewmh_struts
# pointer_action1
# pointer_action2
# pointer_action3
# pointer_follows_focus
# pointer_follows_monitor
# pointer_modifier
# pointer_motion_interval
